name: Merge Pal (events)

on:
  push: {} 
  status: {} 
  pull_request_review: 
    types:
      - submitted
      - edited
      - dismissed
  pull_request: 
    types:
      - labeled
      - unlabeled

jobs:
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}